### ISSUE TITLE
Document that Engine strips some headers from traces as Private automatically

### ISSUE THREAD

**Issue by daniman** [apollographql/engine-docs#154]
Engine strips out "Authorization", "Cookie", and "Set-Cookie" headers from all traces automatically (marking them as private), even if users don't ask. This has led to some questions in support because it's undocumented – users who notice that some headers are stripped want to know exactly which ones are.

**Comment by glasser** [comment]
We could document this alongside privateHeaders since what these are are really just hardcoded (unremovable) members of that list.

We should also consider replacing with `(redacted)` like we do for variables (though it would be nice to change the report format so that's a boolean or something rather than a magic special value, maybe?)

**Comment by daniman** [comment]
Let's close this for now because I did slip this into the Data Privacy doc. We can open a new issue if it continues to be a problem.
